Fix/collapsible en veel meer
fosopenscouting/saamdagen pull request #292
Opened 2024-11-14 09:50 UTC by TijlS

## Includes 
- #289 

## Fixes
- #291 
- #288 
- #286 
- #259 

## Confirmation needed
- #287 

## WIP
- #149

2024-11-15 12:06 UTC, thomasdewulf requested changes
Zie comments in de files. Voor de rest zou ik er willen voor opteren om in de toekomst iets kleinere PRs te maken. Maakt het iets makkelijker om te reviewen. Zeker als er zaken zijn zoals een expo SDK upgrade 😄

2024-11-15 12:06 UTC, thomasdewulf commented on screens/DayScreen.tsx
> +    <>
Er zit hier ergens nog eenzelfde bug als bij de andere schermen, er is een margin waardoor de timeline vroeger afsnijdt

2024-11-15 14:38 UTC, TijlS commented on app/(tabs)/more/profile.tsx
>    const showConfirmDialog = () => {
Gebruikte package voor die dialogs was al 4j niet in gebruik, heb een andere gebruikt nu.
Tonen ze nu wel?

2024-11-15 16:20 UTC, thomasdewulf commented on app/(tabs)/more/profile.tsx
>    const showConfirmDialog = () => {
Yes!

2024-11-15 16:21 UTC, thomasdewulf commented on app/(tabs)/schedule/_layout.tsx
>  import useColorScheme from '@/hooks/useColorScheme';
Vrees van niet :(
![1E7DC84F-9CDD-4A73-9C79-129EACAD2248](https://github.com/user-attachments/assets/666ac2a6-f7d3-43b6-be09-e94a64d9025b)

2024-11-15 16:23 UTC, thomasdewulf commented on screens/DayScreen.tsx
> +    <>
still the same for me

2024-11-15 17:03 UTC, TijlS commented on app/(tabs)/schedule/_layout.tsx
>  import useColorScheme from '@/hooks/useColorScheme';
Hmm, raar.
Bij mij doet ie het wel. Zou dit aan IOS liggen?
Zal ook nog eens zoeken.

2024-11-15 18:14 UTC, thomasdewulf commented on app/(tabs)/schedule/_layout.tsx
>  import useColorScheme from '@/hooks/useColorScheme';
Ik probeer dit weekend ook eens om het te fixen

2024-11-16 14:22 UTC, thomasdewulf commented
@TijlS Ik heb een change gepusht die het fix op iOS, maar mss is het weer kapot op Android. Kan je even controleren?

2024-11-16 19:12 UTC, TijlS commented
> @TijlS Ik heb een change gepusht die het fix op iOS, maar mss is het weer kapot op Android. Kan je even controleren?

Op Android werkt het ook nog.
Merci!

2024-11-16 19:24 UTC, thomasdewulf commented
Mag gemerged worden voor mij :)

2024-11-16 19:53 UTC, TijlS commented
Top!
Zal later dan nog eens kijken of #149 nog verbeterd kan worden.

Is het ook best om de versie van 5.2.16 _(Google Play Store)_ naar 6.0.0 te halen, aangezien dit toch een redelijke update is? _(+hoe moet dit? 😅)_

2024-11-17 10:20 UTC, thomasdewulf commented
> Top! Zal later dan nog eens kijken of #149 nog verbeterd kan worden.
> 
> Is het ook best om de versie van 5.2.16 _(Google Play Store)_ naar 6.0.0 te halen, aangezien dit toch een redelijke update is? _(+hoe moet dit? 😅)_

Staat hier: https://github.com/fosopenscouting/saamdagen#versioning
Ik zal het opzetten :)

2024-11-17 10:22 UTC, merged